feat: Add artifact repo configuration
foundry-rs/foundry-toolchain pull request #36
Opened 2023-08-25 07:44 UTC by frank-lim-partior

# Add configuration for artifact repository
Right now, the foundry github action always download artifacts from the official github repository. This change will allow users to use a repository of choice - e.g. via jfrog artifactory.

The change consists of the addition of an optional configuration that defaults to `https://github.com` and should not require any config changes from existing users.

2024-04-09 19:58 UTC, FELIXTHECAT420 requested changes
# clone the repository
git clone https://github.com/foundry-rs/foundry.git
cd foundry
# install Forge
cargo install --path ./crates/forge --profile local --force --locked
# install Cast
cargo install --path ./crates/cast --profile local --force --locked
# install Anvil
cargo install --path ./crates/anvil --profile local --force --locked
# install Chisel
cargo install --path ./crates/chisel --profile local --force --locked

2024-12-19 14:20 UTC, zerosnacks commented
Hi @frank-lim-partior, thanks for your PR and apologies for the late response

Could you expand on your use-case? Generally not opposed to the change

2025-01-20 00:16 UTC, Missjones2829 reviewed
Merge

2025-01-20 00:16 UTC, Missjones2829 commented on dist/index.js.map
Merge

2025-01-20 08:28 UTC, closed without merging